version: '3.9'
services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    restart: always
    volumes:
      - ./src:/app/src

    networks:
      - hi

  database:
    build: ./src/db
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT_STANDART}
    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: always

    networks:
      - hi

volumes:
  postgres-data:


networks:
  hi: 
    driver: bridge